
package arboles;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria
 */
public class VentanaArbol extends javax.swing.JFrame {
    Arbol arbol;    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaArbol.class.getName());

    /**
     * Creates new form VentanaArbol
     */
    public VentanaArbol(Arbol arbol) {
        initComponents();
        this.arbol = arbol;

        PanelArbol panel = new PanelArbol(arbol);

        this.setContentPane(panel);

        this.setSize(1600,900);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Arbol A1 = new Arbol();
        int opcion;

        char Vc[] = JOptionPane
                .showInputDialog("Ingrese la cadena del arbol")
                .toCharArray();
        
        A1.Construir(Vc);
       
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new VentanaArbol(A1).setVisible(true));
        do{

        opcion = Integer.parseInt(

            JOptionPane.showInputDialog(
                        "====== MENU AVL ======\n\n"
                        + "1. Mostrar arbol\n"
                        + "2. Mostrar Preorden\n"
                        + "3. Mostrar Inorden\n"
                        + "4. Mostrar Posorden\n"
                        + "5. Contar las hojas\n"
                        + "6. Contar los Padres\n"
                        + "7. Insertar Dato\n"
                        + "8. Eliminar Dato\n"
                        + "9. Mostrar el hermano\n"
                        + "10. Mostrar el nivel de un dato\n"
                        + "11. Mostrar la altura de un dato\n"
                        + "12. Mostrar los primos Hermanos de un dato\n"
                        + "13. Mostrar los ancestros de un dato\n"
                        + "0. Salir\n"
                )
            );

            switch (opcion) {

                case 1:

                    java.awt.EventQueue.invokeLater(() -> new VentanaArbol(A1).setVisible(true));

                    break;

                case 2:

                    JOptionPane.showMessageDialog(null, "PreOrden: " + A1.preOrden(A1.getRaiz()));

                    break;

                case 3:

                    JOptionPane.showMessageDialog(null, "InOrden: " + A1.InOrden(A1.getRaiz()));
                    break;
                case 4:

                    JOptionPane.showMessageDialog(null, "PosOrden: " + A1.posOrden(A1.getRaiz()));
                    break;
                case 5:
                int hojas=A1.contarHojas(A1.getRaiz());
                JOptionPane.showMessageDialog(null, "Hay " + hojas + " hojas en este arbol ");

               

            break;
            case 6:
                int padres=A1.contarPadres(A1.getRaiz());
                JOptionPane.showMessageDialog(null, "Hay " + padres + " padres en este arbol ");


              

            break;
            case 7:
                
                char vc[] = JOptionPane.showInputDialog("Ingrese la letra o letras que desea Ingresar")
                .toCharArray();
        
                A1.Construir(vc);

                JOptionPane.showMessageDialog(null, "Su letra fue ingresada, presione 1 para mostrar");

            break;
            case 8:
                char nuevo2=JOptionPane.showInputDialog("Digite la letra que desea Eliminar").charAt(0);;
                if (Character.isLetter(nuevo2)) {
                    A1.eliminar(A1.getRaiz(), nuevo2);
                } else {
                    JOptionPane.showMessageDialog(null, "Digite una letra");
                    return;
                }

                JOptionPane.showMessageDialog(null, "Su letra fue eliminada, presione 1 para mostrar");


             
            break;
            
                case 9:

                    char hermano
                            = JOptionPane.showInputDialog(
                                    "Digite la letra al que le desea buscar su hermano"
                            ).charAt(0);

                    Nodo h
                            = A1.mostrarHermano(
                                    A1.getRaiz(),
                                    hermano
                            );

                    if (h != null) {

                        JOptionPane.showMessageDialog(
                                null,
                                "El hermano de "
                                + hermano
                                + " es -> "
                                + h.getDato()
                        );
                    } else {

                        JOptionPane.showMessageDialog(
                                null,
                                "No tiene hermano o no existe"
                        );
                    }

                    break;

            case 10:

                char nivelDato
                        = JOptionPane.showInputDialog(
                                "Digite la letra"
                        ).charAt(0);

                int nivel
                        = A1.mostrarNivel(
                                A1.getRaiz(),
                                nivelDato,
                                0
                        );

                if (nivel != -1) {

                    JOptionPane.showMessageDialog(
                            null,
                            "El nivel de "
                            + nivelDato
                            + " es -> "
                            + nivel
                    );
                } else {

                    JOptionPane.showMessageDialog(
                            null,
                            "El dato no existe"
                    );
                }

            break;
            
            case 11:
                char dato=JOptionPane.showInputDialog("Digite la letra que desea Buscar").charAt(0);;
                if (Character.isLetter(dato)) {

                    int Altura = A1.altura(A1.buscarNodo(A1.getRaiz(), dato));
                    JOptionPane.showMessageDialog(null, "La altura de " + dato + " es -> " + Altura);
                } else {
                    JOptionPane.showMessageDialog(null, "Digite una letra");
                    return;
                }
 
            break;
            
            case 12:

                char primo
                        = JOptionPane.showInputDialog(
                                "Digite el dato"
                        ).charAt(0);

                String primos
                        = A1.mostrarPrimosHermanos(
                                A1.getRaiz(),
                                primo
                        );

                JOptionPane.showMessageDialog(
                        null,
                        "Primos hermanos de "
                        + primo
                        + " -> "
                        + primos
                );


            break;

                case 13:

                    char ancestro
                            = JOptionPane.showInputDialog(
                                    "Digite el dato"
                            ).charAt(0);

                    String ancestros
                            = A1.mostrarAncestros(
                                    A1.getRaiz(),
                                    ancestro
                            );

                    if (!ancestros.equals("")) {

                        JOptionPane.showMessageDialog(
                                null,
                                "Ancestros de "
                                + ancestro
                                + "\n\n"
                                + ancestros
                                + "\n\nEl ultimo ancestro mostrado es el padre"
                        );
                    } else {

                        JOptionPane.showMessageDialog(
                                null,
                                "No tiene ancestros o no existe"
                        );
                    }

                    break;


            case 0:

                JOptionPane.showMessageDialog(
                    null,
                    "Programa finalizado"
                );

            break;

            default:

                JOptionPane.showMessageDialog(
                    null,
                    "Opcion invalida"
                );
        
        }
        } while(opcion!=0);}}
        

          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

