/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arboles;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria
 */
public class VentanaArbol extends javax.swing.JFrame {
    Arbol arbol;    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaArbol.class.getName());

    /**
     * Creates new form VentanaArbol
     */
    public VentanaArbol(Arbol arbol) {
        initComponents();
        this.arbol = arbol;

        PanelArbol panel = new PanelArbol(arbol);

        this.setContentPane(panel);

        this.setSize(800,600);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Arbol A1 = new Arbol();
        int opcion;

        char Vc[] = JOptionPane
                .showInputDialog("Ingrese la cadena del arbol")
                .toCharArray();
        
        A1.Construir(Vc);
       
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new VentanaArbol(A1).setVisible(true));
        do{

        opcion = Integer.parseInt(

            JOptionPane.showInputDialog(

                "====== MENU AVL ======\n\n" +
                
                "1. Mostrar arbol\n" +
                "2. Mostrar Preorden\n" +
                "3. Mostrar Inorden\n" +
                "4. Mostrar Posorden\n" +
                "5. Contar las hojas\n"+
                "6. Contar los Padres\n"+
                "7. Insertar Dato\n" +
                "8. Eliminar Dato\n" +
                "9. Mostrar el hermano\n" +
                "10. Mostrar el nivel de un dato\n" +
                "11. Mostrar la altura de un dato\n"+                      
                "12. Mostrar los primos Hermanos de un dato\n"+
                "13. Mostrar los ancestros de un dato\n"+
                "0. Salir\n"
                        
            )
        );

        switch(opcion){

            case 1:
                

            java.awt.EventQueue.invokeLater(() -> new VentanaArbol(A1).setVisible(true));


            break;

            case 2:

              
                
            break;

            case 3:

                

            break;
            case 4:

               

            break;
            case 5:

               

            break;
            case 6:

              

            break;
            case 7:

                

            break;
            case 8:

             
            break;
            case 9:

               

            break;
            case 10:

               

            break;
            case 11:
                char dato=JOptionPane.showInputDialog("Digite la letra q desea Buscar").charAt(0);;
                int Altura=A1.altura(A1.buscarNodo(A1.getRaiz(), dato));
                JOptionPane.showMessageDialog(null,"La altura de " + dato + " es -> "+ Altura);

                

            break;
            case 12:

                

            break;

            case 13:

                

            break;


            case 0:

                JOptionPane.showMessageDialog(
                    null,
                    "Programa finalizado"
                );

            break;

            default:

                JOptionPane.showMessageDialog(
                    null,
                    "Opcion invalida"
                );
        
        }
        } while(opcion!=0);}}
        

          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

